#!/bin/bash

# ShilpkaarAI Quick Deployment Script
echo "🚀 ShilpkaarAI Quick Deployment"
echo "==============================="

# Your Supabase credentials
SUPABASE_URL="https://ligdkkmdyhzzxkmvvhfb.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZ2Rra21keWh6enhrbXZ2aGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjkxNjAsImV4cCI6MjA3NDA0NTE2MH0.bVRFOmxxzDxF69XI4x3Q5ci-VX55ss0YICNsiQW5MOo"
SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZ2Rra21keWh6enhrbXZ2aGZiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODQ2OTE2MCwiZXhwIjoyMDc0MDQ1MTYwfQ.xUoTElTgu4d06FcPUuka6dzfAqFyH8JacqH8eXDEUUY"

echo "✅ Backend tested successfully with Supabase!"
echo ""
echo "🎯 Next Steps for Deployment:"
echo "============================="
echo ""
echo "1. 📊 Set up Supabase Database Schema:"
echo "   - Go to: https://ligdkkmdyhzzxkmvvhfb.supabase.co"
echo "   - Click 'SQL Editor' → 'New Query'"
echo "   - Copy and paste the contents of 'supabase-schema.sql'"
echo "   - Click 'Run' to create all tables"
echo ""
echo "2. 🌐 Deploy Backend to Vercel:"
echo "   - Go to: https://vercel.com"
echo "   - Click 'New Project'"
echo "   - Import your GitHub repository"
echo "   - Set Root Directory: 'backend'"
echo "   - Add Environment Variables:"
echo "     SUPABASE_URL=$SUPABASE_URL"
echo "     SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
echo "     SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_KEY"
echo "     FRONTEND_URL=https://your-frontend-url.vercel.app"
echo "   - Click 'Deploy'"
echo ""
echo "3. 🎨 Deploy Frontend to Vercel:"
echo "   - Create another Vercel project"
echo "   - Set Root Directory: 'frontend'"
echo "   - Add Environment Variable:"
echo "     VITE_API_URL=https://your-backend-url.vercel.app"
echo "   - Click 'Deploy'"
echo ""
echo "4. 🔄 Update Frontend API URL:"
echo "   - Update VITE_API_URL in Vercel dashboard with backend URL"
echo "   - Redeploy frontend"
echo ""
echo "🎉 Your app will be completely free forever!"
echo "   Total cost: ₹0"
echo ""
echo "📖 For detailed instructions, see DEPLOYMENT_GUIDE.md"
